#!/bin/sh
set -e

###
# Disable our service
###
systemctl stop fvapp-sickrage
if [ -f /lib/systemd/system/fvapp-sickrage.service ]; then
    systemctl disable fvapp-sickrage
fi

###
# Remove compiled python stuff
###
find /apps/sickrage -name "*.pyc" -print0 | xargs -n1 -0 rm -f
find /apps/sickrage -name "*.pyo" -print0 | xargs -n1 -0 rm -f
